# Generated by Django 3.2.4 on 2021-06-12 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahumtemp',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datahumtemp',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='datahumtemp',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
