# Generated by Django 2.2 on 2021-06-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisTool', '0003_auto_20210614_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
