# Generated by Django 3.2.4 on 2021-06-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysisTool', '0004_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahumtemp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
